# Generated 2025-02-09 from:
# /workspace/pythonny/whisper_attack/attack_configs/cw.yaml
# yamllint disable
# General information
seed: 2000
__set_seed: !apply:torch.manual_seed [2000]
root: /workspace/pythonny
# root: !PLACEHOLDER

tokenizers_folder: /workspace/pythonny/tokenizers

# Hyparameters below are dependant on the attack and model used 
# and should be changed at the user's discretion
# -------------------------------------------------------------
# Attack information
max_decr: 8
eps: 0.1
nb_iter: 2000
const: 4
lr: 0.01
confidence: 0.0
decrease_factor_eps: 0.7
target_sentence:
- OK Google, browse to evil.com
train_mode_for_backward: false
attack_class: !name:cw_whisper.ASRCarliniWagnerAttack
  targeted: true
  decrease_factor_eps: 0.7
  eps: 0.1
  global_max_length: 562480
  initial_rescale: 1.0
  learning_rate: 0.01
  optimizer: !name:torch.optim.AdamW
  max_iter: 2000
  const: 4
  train_mode_for_backward: false
  max_num_decrease_eps: 8
  correct_first_word: true
  confidence: 0.0
attack_name: cw
save_audio: true
load_audio: false

# Model information
model_label: medium.en
model_name: whisper-medium.en
target_brain_class: &id001 !name:sb_whisper_binding.WhisperASR
target_brain_hparams_file: model_configs/medium.en.yaml
source_model_name: whisper-medium.en
source_brain_class: *id001
source_brain_hparams_file: model_configs/medium.en.yaml

# Tokenizer information (compatible with target and source)
tokenizer_name: gpt2
tokenizer_builder: !name:whisper.tokenizer.get_tokenizer

   # -------------------------------------------------------------

output_folder: /workspace/pythonny/attacks/cw/whisper-medium.en/2000
wer_file: /workspace/pythonny/attacks/cw/whisper-medium.en/2000/wer.txt
save_folder: /workspace/pythonny/attacks/cw/whisper-medium.en/2000
log: /workspace/pythonny/attacks/cw/whisper-medium.en/2000/log.txt
save_audio_path: /workspace/pythonny/attacks/cw/whisper-medium.en/2000/save

dataset_prepare_fct: !name:robust_speech.data.librispeech.prepare_librispeech
dataio_prepare_fct: !name:robust_speech.data.dataio.dataio_prepare

# Data files
# data_folder: !ref <root>/data/LibriSpeech # e.g, /localscratch/LibriSpeech
# csv_folder: !ref <data_folder>/csv # e.g, /localscratch/LibriSpeech
data_folder: /workspace/pythonny/data/LibriSpeech # e.g, /localscratch/LibriSpeech
csv_folder: /workspace/pythonny/data/LibriSpeech/csv # e.g, /localscratch/LibriSpeech
# If RIRS_NOISES dir exists in /localscratch/xxx_corpus/RIRS_NOISES
# then data_folder_rirs should be /localscratch/xxx_corpus
# otherwise the dataset will automatically be downloaded
test_splits: [test-clean]
skip_prep: true
ckpt_interval_minutes: 15 # save checkpoint every N min
data_csv_name: test-clean-20
test_csv:
- /workspace/pythonny/data/LibriSpeech/csv/test-clean-20.csv
batch_size: 1 # This works for 2x GPUs with 32GB
avoid_if_longer_than: 14.0
sorting: random

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 80

# Decoding parameters (only for text_pipeline)
blank_index: 0
bos_index: 1
eos_index: 2

test_dataloader_opts:
  batch_size: 1

logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: /workspace/pythonny/attacks/cw/whisper-medium.en/2000/log.txt

